# Generated by Django 4.2.30 on 2026-07-23 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name_sw', models.CharField(max_length=160, verbose_name='name in Kiswahili')),
                ('name_en', models.CharField(max_length=160, verbose_name='name in English')),
                ('code', models.CharField(max_length=40, verbose_name='council code')),
                ('council_type', models.CharField(choices=[('CITY', 'City Council'), ('MUNICIPAL', 'Municipal Council'), ('TOWN', 'Town Council'), ('DISTRICT', 'District Council'), ('ZANZIBAR_MUNICIPAL', 'Municipal Council - Zanzibar'), ('ZANZIBAR_TOWN', 'Town Council - Zanzibar'), ('ZANZIBAR_DISTRICT', 'District Council - Zanzibar'), ('OTHER', 'Other')], default='DISTRICT', max_length=30, verbose_name='council type')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='slug')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='councils', to='core.region', verbose_name='region')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'council',
                'verbose_name_plural': 'councils',
                'ordering': ['region__name_sw', 'name_sw'],
            },
        ),
        migrations.AddConstraint(
            model_name='council',
            constraint=models.UniqueConstraint(fields=('region', 'code'), name='unique_council_code_per_region'),
        ),
        migrations.AddConstraint(
            model_name='council',
            constraint=models.UniqueConstraint(fields=('region', 'name_sw'), name='unique_council_name_sw_per_region'),
        ),
    ]
