# Generated by Django 4.2.30 on 2026-08-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_enable_staff_for_operational_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Administrator'), ('EVENT_ADMIN', 'Event Administrator'), ('REGISTRATION_OFFICER', 'Registration Officer'), ('ATTENDANCE_OFFICER', 'Attendance Officer'), ('REPORT_OFFICER', 'Report Officer'), ('DIRECTOR', 'Director'), ('PARTICIPANT', 'Participant')], default='PARTICIPANT', max_length=30, verbose_name='role'),
        ),
    ]
